### ISSUE TITLE
Add a handler for closed() attribute on MediaKeySession

### ISSUE THREAD

**Issue by xhwang-chromium** [google/eme_logger#20]
`MediaKeySession` `closed()` attribute returns a promise which could be resolved when the sessions is closed either by an explicit `close()` call or some implicit reason. Currently EME logger doesn't handle `closed()` so if the session is closed by itself we won't see any logs.

It'd be nice to add a handler for the `closed()` attribute, so we can get a notification, and be able to see the `MediaKeySessionClosedSession`.

**Comment by joeyparrish** [comment]
Resolved in v3.0.0 release.  Promise-based attributes are now displayed in a way similar to events.
