### ISSUE TITLE
Support MediaCapabilities::decodingInfo()

### ISSUE THREAD

**Issue by xhwang-chromium** [google/eme_logger#21]
[`MediaCapabilities::decodingInfo()`](https://www.w3.org/TR/media-capabilities/#dictdef-mediacapabilitiesdecodinginfo) is a new way to create `MediaKeySystemAccess`. In other words, it's another entry point to EME APIs. Currently this new entry point is not supported by EME logger, and it appears all operations on the `MediaKeySession` are not logged because of this either.

Now more and more sites start to use `MediaCapabilities::decodingInfo()`. We should support it in EME logger.

**Comment by joeyparrish** [comment]
Resolved in v3.0.0 release
