### ISSUE TITLE
Show MediaKeyMessageEvent.messageType

### ISSUE THREAD

**Issue by xhwang-chromium** [google/eme_logger#27]
Currently `MediaKeyMessageEvent` is displayed as `MediaKeySession message event` where only the `message` is shown. It'd be great to also see the `MediaKeyMessageEvent.messageType`, e.g. `license-request` or `license-renewal`.

See the screenshot below for the current behavior:

<img width="458" alt="Capture" src="https://user-images.githubusercontent.com/10169438/144491060-37dd2ba2-ab63-402c-8c03-ffaf07af069a.PNG">

**Comment by joeyparrish** [comment]
I'm not sure why that's not showing.  I'll take a look.

**Comment by joeyparrish** [comment]
Where we hook in the formatter, we're using a spread operator to copy all the fields of the original to the formatted version:

```js
    // You can't (and shouldn't, to avoid breaking the app) modify the event
    // object here.  So clone it, and replace the message field of that.
    log.event = {
      // The spread operator reads the fields and values (shallow clone) of the
      // object named here.
      ...log.event,
      // This overrides on of those fields with a new value.
      message: formatEmeRequest(log.event.message),
    };
```

It's not working, though.  Only `isTrusted` gets copied by the spread operator.

**Comment by joeyparrish** [comment]
It appears that the difference is in "own" properties.  The spread operator seems to only copy an object's "own" properties, and this object's only "own" property is `isTrusted`.

```js
orig
MediaKeyMessageEvent {isTrusted: true, messageType: 'license-request', message: ArrayBuffer(2), type: 'message', target: MediaKeySession, …}

{...orig}
{isTrusted: true}

Object.keys(orig)
['isTrusted']

JSON.stringify(orig)
'{"isTrusted":true}'

a = []; for (k in orig) { a.push(k); }; a;
(25) ['isTrusted', 'messageType', 'message', 'type', 'target', 'currentTarget', 'eventPhase', 'bubbles', 'cancelable', 'defaultPrevented', 'composed', 'timeStamp', 'srcElement', 'returnValue', 'cancelBubble', 'path', 'NONE', 'CAPTURING_PHASE', 'AT_TARGET', 'BUBBLING_PHASE', 'composedPath', 'initEvent', 'preventDefault', 'stopImmediatePropagation', 'stopPropagation']

for (k in orig) { if (orig.hasOwnProperty(k)) console.log(k); }
isTrusted
```

**Comment by joeyparrish** [comment]
Object.assign has the same drawback as the spread operator and Object.keys:

```js
Object.assign({}, orig)
{isTrusted: true}
```

Thinking about "own" properties, though, it seems I can just filter out the properties inherited from Event:

```js
for (k in orig) { if (!Event.prototype.hasOwnProperty(k)) console.log(k); }
isTrusted
messageType
message
```

I should be able to write a custom cloning method for Event objects to ensure the copy has everything it should.
